### ISSUE TITLE
HTTP API JWT Authorizer - "nbt" or "iat" claims?

### ISSUE THREAD

**Issue by rrrix** [awsdocs/amazon-api-gateway-developer-guide#76]
Hi! 

I think the documentation may be missing "iat" claim instead of the "nbt" claim? Or maybe the HTTP API optionally checks the "nbt" claim only if it's present and ignores the "iat" claim?

AWS Cognito issues Access (OAuth 2.0) and Id (OIDC) Tokens that do not include an "nbt" field (Not-Before) claim, rather, it includes an "iat" (Issued-At) claim. See https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html#amazon-cognito-user-pools-using-the-access-token for reference.

Here's the example payload from "Access Token Payload":

```yaml
{
  "sub": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
  "device_key": "us-west-2_"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
  "cognito:groups": [
    "admin"
  ],
  "token_use": "access",
  "scope": "aws.cognito.signin.user.admin",
  "auth_time": 1562190524,
  "iss": "https://cognito-idp.us-west-2.amazonaws.com/us-west-2_example",
  "exp": 1562194124,
  "iat": 1562190524,
  "jti": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
  "client_id": "57cbishk4j24pabc1234567890",
  "username": "janedoe@example.com"
} 
```

I was trying to confirm (via the documentation) that I am able to use Use Cognito JWT Access Tokens with HTTP JWT Authorizors. 

The Amazon Cognito JWT Access Token does NOT include an "nbt" (Not-Before) claim https://tools.ietf.org/html/rfc7519#section-4.1.5

The Amazon Cognito JWT Access Token does include an "iat" (Issued-At) claim, however: https://tools.ietf.org/html/rfc7519#section-4.1.6

Do API Gateway HTTP API's support validating with the "iat" (Issued-At) claim if the "nbt" (Not-Before) claim is not present, as per Amazon Cognito Access Token Payload? 

I've also verified myself with my own application that Amazon Cognito does not include an "nbt" claim, but rather an "iat" claim in the Access and ID JWT Tokens.
